# CodeRabbit Configuration

# Review settings
reviews:
  # Enable automated review for pull requests
  auto_review:
    enabled: false
    base_branches:
      - ".*" # Matches all branches using regex
  review_status: false
  poem: false
  high_level_summary: false
  path_filters:
    - "!apps/demo/**" # exclude the demo app from reivews
