import { type Metadata } from "next";
import "@/config/theme/globals.css";

export const metadata: Metadata = {
  title: "My ProofKit App",
  description: "Generated by proofkit",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-dvh bg-white text-black antialiased dark:bg-black dark:text-white">
        {children}
      </body>
    </html>
  );
}
