import { type Metadata } from "next";
import "@/config/theme/globals.css";

export const metadata: Metadata = {
  title: "My ProofKit App",
  description: "Generated by proofkit",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

import { Geist, Geist_Mono } from "next/font/google";

import Providers from "@/components/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
