/**
 * Generated by @proofkit/typegen package
 * https://proofkit.dev/docs/typegen
 * DO NOT EDIT THIS FILE DIRECTLY. Changes may be overritten
 */
import { DataApi, OttoAdapter, type OttoAPIKey } from "@proofkit/fmdapi";
import { ZweirdPortals, ZweirdPortalsPortals } from "../weirdPortals";

// @generated
// prettier-ignore
/* eslint-disable */
if (!process.env.DIFFERENT_FM_DATABASE) throw new Error("Missing env var: DIFFERENT_FM_DATABASE")
if (!process.env.DIFFERENT_FM_SERVER)
  throw new Error("Missing env var: DIFFERENT_FM_SERVER");
if (!process.env.DIFFERENT_OTTO_API_KEY)
  throw new Error("Missing env var: DIFFERENT_OTTO_API_KEY");
if (!process.env.FM_USERNAME) throw new Error("Missing env var: FM_USERNAME");
if (!process.env.FM_PASSWORD) throw new Error("Missing env var: FM_PASSWORD");

export const client = DataApi({
  adapter: new OttoAdapter({
    auth: { apiKey: process.env.DIFFERENT_OTTO_API_KEY as OttoAPIKey },
    db: process.env.DIFFERENT_FM_DATABASE,
    server: process.env.DIFFERENT_FM_SERVER,
  }),
  layout: "Weird Portals",
  schema: { fieldData: ZweirdPortals, portalData: ZweirdPortalsPortals },
});
